using System.Text;
using DntSite.Web.Features.News.Services.Contracts;
using Microsoft.AspNetCore.WebUtilities;
using YoutubeExplode;
using YoutubeExplode.Videos;

namespace DntSite.Web.Features.News.Services;

public class YoutubeScreenshotsService(BaseHttpClient baseHttpClient, ILogger<YoutubeScreenshotsService> logger)
    : IYoutubeScreenshotsService
{
    public async Task<byte[]?> TryGetYoutubeVideoThumbnailDataAsync(string? videoId)
    {
        try
        {
            if (videoId.IsEmpty())
            {
                return null;
            }

            var thumbnailUrl = $"https://i.ytimg.com/vi/{videoId}/hqdefault.jpg";

            return await baseHttpClient.HttpClient.DownloadDataAsync(thumbnailUrl);
        }
        catch (Exception ex)
        {
            logger.LogError(ex.Demystify(), message: "GetYoutubeVideThumbnailAsync({ID}) Error", videoId);

            return null;
        }
    }

    public (bool Success, string? VideoId) IsYoutubeVideo(string? url)
    {
        if (string.IsNullOrWhiteSpace(url))
        {
            return (false, null);
        }

        var uri = new Uri(url);

        if (uri.Host.Contains(value: ".youtube.", StringComparison.OrdinalIgnoreCase) && uri.Segments.Length >= 3 &&
            (uri.Segments[1].Equals(value: "embed/", StringComparison.OrdinalIgnoreCase) ||
             uri.Segments[1].Equals(value: "shorts/", StringComparison.OrdinalIgnoreCase)))
        {
            return (true, uri.Segments[2]);
        }

        if (uri.Host.Contains(value: ".youtube.", StringComparison.OrdinalIgnoreCase))
        {
            var queryDictionary = QueryHelpers.ParseQuery(uri.Query);

            return !queryDictionary.TryGetValue(key: "v", out var v) ? (false, null) : (true, v.ToString());
        }

        if (uri.Host.EndsWith(value: "youtu.be", StringComparison.OrdinalIgnoreCase) && uri.Segments.Length >= 2)
        {
            return (true, uri.Segments[1]);
        }

        return (false, null);
    }

    public async Task<string?> GetYoutubeVideoDescriptionAsync(string? url)
    {
        if (url.IsEmpty())
        {
            return null;
        }

        using var client = new YoutubeClient(baseHttpClient.HttpClient);
        var videoId = VideoId.TryParse(url);

        if (!videoId.HasValue)
        {
            return null;
        }

        var video = await client.Videos.GetAsync(videoId.Value);

        var transcriptBuilder = new StringBuilder();

        try
        {
            var manifest = await client.Videos.ClosedCaptions.GetManifestAsync(video.Id);

            var closedCaptionTrackInfo = manifest.Tracks
                .OrderByDescending(t => t.Language.Name.Contains(value: "English", StringComparison.OrdinalIgnoreCase))
                .ThenByDescending(t => t.IsAutoGenerated)
                .FirstOrDefault();

            if (closedCaptionTrackInfo is not null)
            {
                var closedCaptionTrack = await client.Videos.ClosedCaptions.GetAsync(closedCaptionTrackInfo);

                foreach (var closedCaption in closedCaptionTrack.Captions)
                {
                    var text = closedCaption.Text;

                    if (text.IsEmpty())
                    {
                        continue;
                    }

                    if (transcriptBuilder.Length > 0)
                    {
                        transcriptBuilder.Append(value: ' ');
                    }

                    transcriptBuilder.Append(text);
                }
            }
        }
        catch (Exception ex)
        {
            logger.LogError(ex.Demystify(), message: "GetYoutubeVideoDescriptionAsync({ID}) Error", videoId);
        }

        return $"{video.Title} {video.Description} {transcriptBuilder}".Trim();
    }
}
